### ISSUE TITLE
Question about activity lifecycle.

### ISSUE THREAD

**Issue by Stoff81** [awsdocs/aws-android-developer-guide#12]
Hey, 

I am integrated Mobile Analytics into our application. According to your documentation you suggest that onResume/onPause be implemented to pause and resume the session and send events. In our application we have many Activities so it seems a bit strange to be constantly be pausing/resuming the session every time the user goes to a different page or activity.

What do you suggest? Ideally I would just like to pause the session when going to background and sending events when closing the app.

**Comment by ebattalio** [comment]
Hi,

If you have not already done so, you can try posting your question to https://forums.aws.amazon.com/forum.jspa?forumID=174. 

Thanks!
Eric
