### ISSUE TITLE
build_docs.py script fails with configuration error

### ISSUE THREAD

**Issue by SCalwas** [awsdocs/aws-android-developer-guide#17]
Run the build_docs.py script with Python 3.7.1 and Sphinx 1.8.2.
Fails with the message "Configuration error: There is a programmable error in your configuration file: NameError: name 'html_theme_options' is not defined'

The build file might have been written for an older version of Sphinx. The data type of html_theme_options in the script does not match the expected type in the current version of Sphinx. There are other errors after this one is cleaned up.

**Comment by ebattalio** [comment]
Hi, thanks for the feedback. 

Is this still an problem? If so, open/reopen an issue.

Thanks!
Eric
