### ISSUE TITLE
Missing close bracket on DynamoDB page

### ISSUE THREAD

**Issue by tclemente** [awsdocs/aws-android-developer-guide#9]
Page: https://github.com/awsdocs/aws-android-developer-guide/blob/master/doc_source/dynamodb_om.rst#interact-with-stored-objects

Issue: The first code blob in this section is missing a closing bracket around the run() method

**Comment by dzucker-amzn** [comment]
Thanks for the catch, I accepted your pull request.

**Comment by dzucker-amzn** [comment]
closing
